sonar.projectKey=PythonProject
sonar.projectName=PythonProject
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqa_0f717fc3bb7d12a11f6165807e6fcf1762991d8f
